query GetClientData($id: String!) {
  client(id: $id) {
    # Запрашиваем только имена всех родственников клиента
    relatives {
      name
    }
    
    # Запрашиваем номера всех документов клиента
    # Первый документ можно обработать на клиенте (например, взять documents[0].number)
    documents {
      number
    }
  }
}
